/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MavenRouteImport } from './routes/maven'
import { Route as MavenIndexRouteImport } from './routes/maven.index'
import { Route as MavenAdminRouteImport } from './routes/maven.admin'
import { Route as MavenInterviewRouteImport } from './routes/maven.interview'
import { Route as MavenNotesRouteImport } from './routes/maven.notes'
import { Route as MavenQuizRouteImport } from './routes/maven.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MavenRoute = MavenRouteImport.update({
  id: '/maven',
  path: '/maven',
  getParentRoute: () => rootRouteImport,
} as any)
const MavenIndexRoute = MavenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MavenRoute,
} as any)
const MavenAdminRoute = MavenAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MavenRoute,
} as any)
const MavenInterviewRoute = MavenInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => MavenRoute,
} as any)
const MavenNotesRoute = MavenNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => MavenRoute,
} as any)
const MavenQuizRoute = MavenQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => MavenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maven': typeof MavenRouteWithChildren
  '/maven/admin': typeof MavenAdminRoute
  '/maven/interview': typeof MavenInterviewRoute
  '/maven/notes': typeof MavenNotesRoute
  '/maven/quiz': typeof MavenQuizRoute
  '/maven/': typeof MavenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maven/admin': typeof MavenAdminRoute
  '/maven/interview': typeof MavenInterviewRoute
  '/maven/notes': typeof MavenNotesRoute
  '/maven/quiz': typeof MavenQuizRoute
  '/maven': typeof MavenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maven': typeof MavenRouteWithChildren
  '/maven/admin': typeof MavenAdminRoute
  '/maven/interview': typeof MavenInterviewRoute
  '/maven/notes': typeof MavenNotesRoute
  '/maven/quiz': typeof MavenQuizRoute
  '/maven/': typeof MavenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maven'
    | '/maven/admin'
    | '/maven/interview'
    | '/maven/notes'
    | '/maven/quiz'
    | '/maven/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maven/admin'
    | '/maven/interview'
    | '/maven/notes'
    | '/maven/quiz'
    | '/maven'
  id:
    | '__root__'
    | '/'
    | '/maven'
    | '/maven/admin'
    | '/maven/interview'
    | '/maven/notes'
    | '/maven/quiz'
    | '/maven/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MavenRoute: typeof MavenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maven': {
      id: '/maven'
      path: '/maven'
      fullPath: '/maven'
      preLoaderRoute: typeof MavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maven/': {
      id: '/maven/'
      path: '/'
      fullPath: '/maven/'
      preLoaderRoute: typeof MavenIndexRouteImport
      parentRoute: typeof MavenRoute
    }
    '/maven/admin': {
      id: '/maven/admin'
      path: '/admin'
      fullPath: '/maven/admin'
      preLoaderRoute: typeof MavenAdminRouteImport
      parentRoute: typeof MavenRoute
    }
    '/maven/interview': {
      id: '/maven/interview'
      path: '/interview'
      fullPath: '/maven/interview'
      preLoaderRoute: typeof MavenInterviewRouteImport
      parentRoute: typeof MavenRoute
    }
    '/maven/notes': {
      id: '/maven/notes'
      path: '/notes'
      fullPath: '/maven/notes'
      preLoaderRoute: typeof MavenNotesRouteImport
      parentRoute: typeof MavenRoute
    }
    '/maven/quiz': {
      id: '/maven/quiz'
      path: '/quiz'
      fullPath: '/maven/quiz'
      preLoaderRoute: typeof MavenQuizRouteImport
      parentRoute: typeof MavenRoute
    }
  }
}

interface MavenRouteChildren {
  MavenAdminRoute: typeof MavenAdminRoute
  MavenInterviewRoute: typeof MavenInterviewRoute
  MavenNotesRoute: typeof MavenNotesRoute
  MavenQuizRoute: typeof MavenQuizRoute
  MavenIndexRoute: typeof MavenIndexRoute
}

const MavenRouteChildren: MavenRouteChildren = {
  MavenAdminRoute: MavenAdminRoute,
  MavenInterviewRoute: MavenInterviewRoute,
  MavenNotesRoute: MavenNotesRoute,
  MavenQuizRoute: MavenQuizRoute,
  MavenIndexRoute: MavenIndexRoute,
}

const MavenRouteWithChildren = MavenRoute._addFileChildren(MavenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MavenRoute: MavenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
